kind: ConfigMap
apiVersion: v1
metadata:
  name: module-keycloak
data:
  module-keycloak.json: |
    {
      "apiVersion": "argoproj.io/v1alpha1",
      "kind": "Application",
      "metadata": {
        "name": "{{ .Values.module.module_keycloak.name }}",
        "namespace": "{{ .Values.module.module_keycloak.namespace }}",
        "finalizers": [
          "resources-finalizer.argocd.argoproj.io/foreground"
        ]
      },
      "spec": {
        "destination": {
          "name": "",
          "namespace": "{{ .Values.module.module_keycloak.destination.namespace }}",
          "server": "https://kubernetes.default.svc"
        },
        "project": "default",
        "syncPolicy": {
          "automated": {
            "prune": false,
            "selfHeal": false
          }
        },
        "source": {
          "repoURL": "{{ .Values.module.module_keycloak.source.repoUrl }}",
          "targetRevision": "{{ .Values.module.module_keycloak.source.targetRevision }}",
          "path": "{{ .Values.module.module_keycloak.source.path }}",
          "helm": {
            "values": "\ntargetNamespaces: globex-keycloak-{{ .Values.variable.user }}\n"
          }
        }
      },
      "clusterResourceWhitelist": [
        {
          "apiGroups": [""],
          "kind": "Namespace",
          "name": "{{ .Values.module.module_keycloak.namespace }}"
        }
      ],
      "clusterRoleBindings": [
        {
          "name": "argocd-cluster-admin-binding",
          "subjects": [
            {
              "kind": "ServiceAccount",
              "name": "globex-gitops-{{ .Values.variable.user }}-argocd-application-controller",
              "namespace": "{{ .Values.module.module_keycloak.namespace }}"
            }
          ]
        }
      ]
    }
